In [1]:
#Q.1   Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.arange(6)

# Print the array and its data type
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int64


In [3]:
#Q.2   . Given a NumPy array 'arr', check if its data type is float64.


# Given array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("The data type is float64.")
else:
    print("The data type is not float64.")


The data type is float64.


In [4]:
#Q.3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers


arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print(arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


In [5]:
#Q.4  . Convert an existing NumPy array 'arr' of integers to float32 data type.



arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


In [6]:
#Q.5   Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

# Convert the array to float32 to reduce precision
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)


[1.1234568 2.9876542 3.456789 ]
float32


In [7]:
#Q.6  Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


def array_attributes(arr):
    # Return a tuple containing the shape, size, and data type of the array
    return arr.shape, arr.size, arr.dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Data type: {dtype}")


Shape: (2, 3)
Size: 6
Data type: int64


In [8]:
#Q.7   Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


def array_dimension(arr):
    # Return the dimensionality of the array
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print(f"The dimensionality of the array is: {dimension}")


The dimensionality of the array is: 2


In [9]:
#Q.8   Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


def item_size_info(arr):
    # Get the size of each element in bytes (item size)
    item_size = arr.itemsize
    
    # Get the total size of the array in bytes
    total_size = arr.nbytes
    
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)

print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")


Item size: 4 bytes
Total size: 24 bytes


In [10]:
#Q.9  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


def array_strides(arr):
    # Return the strides of the array
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)

print(f"Strides: {strides}")


Strides: (12, 4)


In [11]:
#Q.10    Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.



def shape_stride_relationship(arr):
    # Return the shape and strides of the array
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)

print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (12, 4)


In [12]:
#Q.11  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.



def create_zeros_array(n):
    # Create and return an array of zeros with n elements
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)

print(f"Array of zeros with {n} elements: {zeros_array}")


Array of zeros with 5 elements: [0. 0. 0. 0. 0.]


In [13]:
#Q.12  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.


def create_ones_matrix(rows, cols):
    # Create and return a 2D NumPy array of ones with the given rows and columns
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print(f"Ones matrix of size {rows}x{cols}:\n{ones_matrix}")


Ones matrix of size 3x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#Q.13   Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range
#     starting from `start`, ending at stop (exclusive), and with the specified `step`.



def generate_range_array(start, stop, step):
    # Create and return a NumPy array with the specified range
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print(f"Range array from {start} to {stop} with step {step}:\n{range_array}")


Range array from 0 to 10 with step 2:
[0 2 4 6 8]


In [15]:
#Q.14   Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy
#       array with num equally spaced values between `start` and `stop` (inclusive).


def generate_linear_space(start, stop, num):
    # Create and return a NumPy array with num equally spaced values between start and stop
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print(f"Linear space array from {start} to {stop} with {num} values:\n{linear_space_array}")


Linear space array from 0.0 to 1.0 with 5 values:
[0.   0.25 0.5  0.75 1.  ]


In [16]:
#Q.15   Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.


def create_identity_matrix(n):
    # Create and return an identity matrix of size n x n
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)

print(f"Identity matrix of size {n}x{n}:\n{identity_matrix}")


Identity matrix of size 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#Q.16   Write a function that takes a Python list and converts it into a NumPy array.


def list_to_numpy_array(py_list):
    # Convert the Python list to a NumPy array
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)

print(f"NumPy array: {numpy_array}")


NumPy array: [1 2 3 4 5]


In [18]:
#Q.17    Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


arr = np.array([1, 2, 3, 4, 5])

# Use numpy.view() to create a new array object with the same data
view_arr = arr.view()

# Display the original array and the new view array
print(f"Original array: {arr}")
print(f"View array: {view_arr}")

# Modify the view array
view_arr[0] = 10

# Display the modified view and the original array to show that they share the same data
print(f"Modified view array: {view_arr}")
print(f"Original array after modifying the view: {arr}")


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified view array: [10  2  3  4  5]
Original array after modifying the view: [10  2  3  4  5]


In [19]:
#Q.18  Write a function that takes two NumPy arrays and concatenates them along a specified axis.


def concatenate_arrays(arr1, arr2, axis):
    # Concatenate the two arrays along the specified axis
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0 (rows):\n", result_axis_0)

# Concatenate along axis 1 (columns)
result_axis_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1 (columns):\n", result_axis_1)


Concatenated along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [20]:
#Q.19   Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.


# Create two arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
arr2 = np.array([[5, 6], [7, 8]])  # Shape (2, 2)

# Concatenate them horizontally (along axis 1)
result = np.concatenate((arr1, arr2), axis=1)

print("Concatenated array along axis 1 (horizontally):\n", result)


Concatenated array along axis 1 (horizontally):
 [[1 2 5 6]
 [3 4 7 8]]


In [21]:
#Q.20  . Write a function that vertically stacks multiple NumPy arrays given as a list.


def vertical_stack_arrays(arrays):
    # Stack the list of arrays vertically (along axis 0)
    return np.vstack(arrays)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

# Stack the arrays vertically
stacked_array = vertical_stack_arrays([arr1, arr2, arr3])

print("Vertically stacked arrays:\n", stacked_array)


Vertically stacked arrays:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
#Q.21   Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range_array(start, stop, step):
    # Create an array of integers from start to stop (inclusive) with the specified step size
    # Adjust stop to be inclusive by adding step if needed
    if (stop - start) % step == 0:
        return np.arange(start, stop + step, step)  # Include the stop value
    else:
        return np.arange(start, stop, step)

# Example usage
start = 1
stop = 10
step = 2
range_array = create_range_array(start, stop, step)

print(f"Array with values from {start} to {stop} with step {step}:\n{range_array}")


Array with values from 1 to 10 with step 2:
[1 3 5 7 9]


In [23]:
#Q.22   Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


def generate_equally_spaced_array(start, stop, num_values):
    # Generate an array of equally spaced values between start and stop (inclusive)
    return np.linspace(start, stop, num_values)

# Example usage
start = 0
stop = 1
num_values = 10

array = generate_equally_spaced_array(start, stop, num_values)

print(f"Array of {num_values} equally spaced values between {start} and {stop}:\n{array}")


Array of 10 equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [24]:
#Q.23   Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


def generate_log_spaced_array(start, stop, num_values):
    # Generate a logarithmically spaced array between start and stop (inclusive)
    return np.logspace(np.log10(start), np.log10(stop), num_values)

# Example usage
start = 1
stop = 1000
num_values = 5

log_spaced_array = generate_log_spaced_array(start, stop, num_values)

print(f"Array of {num_values} logarithmically spaced values between {start} and {stop}:\n{log_spaced_array}")


Array of 5 logarithmically spaced values between 1 and 1000:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [25]:
#Q.24   Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

def create_random_dataframe(rows, cols):
    # Create a NumPy array with random integers between 1 and 100
    data = np.random.randint(1, 101, size=(rows, cols))
    
    # Create a DataFrame from the NumPy array
    df = pd.DataFrame(data, columns=[f'Column{i+1}' for i in range(cols)])
    
    return df

# Example usage
rows = 5
cols = 3

random_dataframe = create_random_dataframe(rows, cols)

print("Pandas DataFrame with random integers:\n", random_dataframe)


Pandas DataFrame with random integers:
    Column1  Column2  Column3
0       73       93       96
1        6       68        3
2        7       30       63
3       70       31       84
4       62       78       35


In [26]:
#Q.25  . Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


def replace_negative_with_zero(df, column_name):
    # Replace negative values in the specified column with zeros using NumPy's where function
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    
    return df

# Example usage
# Create a sample DataFrame
data = {'A': [1, -2, 3, -4, 5],
        'B': [-10, 20, -30, 40, -50]}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A' with zeros
df_modified = replace_negative_with_zero(df, 'A')

print("\nDataFrame after replacing negative values in column 'A' with zeros:")
print(df_modified)


Original DataFrame:
   A   B
0  1 -10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

DataFrame after replacing negative values in column 'A' with zeros:
   A   B
0  1 -10
1  0  20
2  3 -30
3  0  40
4  5 -50


In [27]:
#Q.26   Access the 3rd element from the given NumPy array.

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


In [28]:
#Q.27   Retrieve the element at index (1, 2) from the 2D NumPy array.

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


In [29]:
#Q.28  Using boolean indexing, extract elements greater than 5 from the given NumPy array.


# Given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", greater_than_5)


Elements greater than 5: [ 8 10  7]


In [30]:
#Q.29   Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Extracted elements:", sliced_array)


Extracted elements: [3 4 5 6]


In [31]:
#Q.30    Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.


# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:\n", sub_array)


Extracted sub-array:
 [[2 3]
 [5 6]]


In [32]:
#Q.31  Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.


def extract_elements_by_indices(arr_2d, indices):
    # Extract the elements based on the indices
    # indices is expected to be a 2D array with shape (n, 2), where each row is [row_index, col_index]
    row_indices = indices[:, 0]  # Extract row indices
    col_indices = indices[:, 1]  # Extract column indices
    
    # Use fancy indexing to extract the elements
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices array where each row is [row_index, col_index]
indices = np.array([[0, 1],  # Extract element at (0, 1)
                    [1, 2],  # Extract element at (1, 2)
                    [2, 0]]) # Extract element at (2, 0)

# Extract elements based on indices
extracted = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements:", extracted)


Extracted elements: [2 6 7]


In [33]:
#Q.32  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements_greater_than_threshold(arr, threshold):
    # Create a boolean mask where elements greater than the threshold are True
    mask = arr > threshold
    
    # Use the mask to filter elements greater than the threshold
    filtered_elements = arr[mask]
    
    return filtered_elements

# Example usage
arr = np.array([1, 3, 5, 7, 9, 11, 13])
threshold = 6

# Filter elements greater than the threshold
filtered_arr = filter_elements_greater_than_threshold(arr, threshold)

print(f"Filtered elements greater than {threshold}:", filtered_arr)


Filtered elements greater than 6: [ 7  9 11 13]


In [34]:
#Q.33   Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.



def extract_elements_from_3d_array(arr_3d, depth_indices, row_indices, col_indices):
    # Use the provided indices for each dimension to extract the elements
    extracted_elements = arr_3d[depth_indices, row_indices, col_indices]
    
    return extracted_elements

# Example usage
# Create a 3D NumPy array (2x3x4)
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
                   
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

# Indices for each dimension
depth_indices = np.array([0, 1, 0])  # Depth index (2 elements, for two depths)
row_indices = np.array([1, 2, 0])    # Row index
col_indices = np.array([2, 3, 1])    # Column index

# Extract the elements using the indices
extracted_elements = extract_elements_from_3d_array(arr_3d, depth_indices, row_indices, col_indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [ 7 24  2]


In [35]:
#Q.34   Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.



def filter_elements_by_conditions(arr, condition1, condition2):
    # Apply both conditions using logical AND (&)
    filtered_elements = arr[condition1 & condition2]
    
    return filtered_elements

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define two conditions:
condition1 = arr > 3  # Condition 1: Elements greater than 3
condition2 = arr < 8  # Condition 2: Elements less than 8

# Filter elements where both conditions are satisfied
filtered_arr = filter_elements_by_conditions(arr, condition1, condition2)

print("Filtered elements where both conditions are satisfied:", filtered_arr)


Filtered elements where both conditions are satisfied: [4 5 6 7]


In [36]:
#Q.35   Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    # Use row and column indices to extract elements using advanced indexing
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row and column indices (separate arrays)
row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([2, 1, 0])  # Column indices

# Extract the elements using the row and column indices
extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [3 5 7]


In [37]:
#Q.36   Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


# Given 3x3 NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add scalar value 5 to each element of the array using broadcasting
result = arr + 5

print("Result after adding 5 to each element:")
print(result)


Result after adding 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
#Q.37    Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.


# Given arrays
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1

print("Result of row-wise multiplication:")
print(result)


ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [40]:
#Q.38  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.


# Given arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to be broadcastable to arr2's shape
# arr1 has shape (1, 4), and arr2 has shape (4, 3)
# We need to adjust the shapes, let's transpose arr2 or align dimensions.

# Here, we transpose arr2 so that we can broadcast arr1 to it
arr2_transposed = arr2.T  # Shape becomes (3, 4)
result = arr2_transposed + arr1.T  # Shape of arr1 becomes (4, 1)

# We transpose back to get the result in original dimensions
result_transposed = result.T

print("Result after broadcasting arr1 to each row of arr2:")
print(result_transposed)


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [41]:
#Q.39    Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

# Given arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])       # Shape (1, 3)

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

print("Result after broadcasting and adding arr1 and arr2:")
print(result)


Result after broadcasting and adding arr1 and arr2:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [42]:
#Q.40   Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]])         # Shape (2, 2)

# Reshape arr2 to make it compatible with arr1 (broadcast along the columns)
arr2_reshaped = arr2[:, :, np.newaxis]  # Add a new axis to make it (2, 2, 1)

# Broadcast arr2_reshaped to match the shape of arr1
result = arr1 * arr2_reshaped

print("Result after broadcasting and multiplication:")
print(result)


Result after broadcasting and multiplication:
[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [43]:
#Q.41  . Calculate column wise mean for the given array:

import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Calculate column-wise mean (mean along axis 0)
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:")
print(column_wise_mean)


Column-wise mean:
[2.5 3.5 4.5]


In [44]:
#Q.42   Find maximum value in each row of the given array: 

import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find the maximum value in each row (along axis 1)
row_max_values = np.amax(arr, axis=1)

print("Maximum value in each row:")
print(row_max_values)


Maximum value in each row:
[3 6]


In [45]:
#Q.43  . For the given array, find indices of maximum value in each column.


# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find indices of maximum value in each column (along axis 0)
max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:")
print(max_indices)


Indices of maximum value in each column:
[1 1 1]


In [46]:
#Q.44 . For the given array, apply custom function to calculate moving sum along rows.


# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Custom function to calculate moving sum along rows
def moving_sum(arr, window_size):
    result = []
    for row in arr:
        row_sum = [np.sum(row[i:i+window_size]) for i in range(len(row) - window_size + 1)]
        result.append(row_sum)
    return np.array(result)

# Define the window size
window_size = 2

# Apply the custom moving sum function
moving_sum_result = moving_sum(arr, window_size)

print("Moving sum along rows:")
print(moving_sum_result)


Moving sum along rows:
[[ 3  5]
 [ 9 11]]


In [47]:
#Q.45   In the given array, check if all elements in each column are even.


# Given array
arr = np.array([[2, 4, 6], 
                [3, 5, 7]])

# Check if all elements in each column are even
all_even_in_columns = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?")
print(all_even_in_columns)


Are all elements in each column even?
[False False False]


In [48]:
#Q.46  . Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.


# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the new shape
m, n = 2, 3  # Example dimensions: 2 rows and 3 columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:")
print(reshaped_matrix)


Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [49]:
#Q.47   Create a function that takes a matrix as input and returns the flattened array.


# Function to flatten the input matrix
def flatten_matrix(matrix):
    return matrix.flatten()  # or use matrix.ravel()

# Given input matrix
input_matrix = np.array([[1, 2, 3], 
                         [4, 5, 6]])

# Call the function and print the result
flattened_array = flatten_matrix(input_matrix)

print("Flattened array:")
print(flattened_array)


Flattened array:
[1 2 3 4 5 6]


In [50]:
#Q.48   Write a function that concatenates two given arrays along a specified axis.


# Function to concatenate two arrays along a specified axis
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0 (rows):")
print(concatenated_axis_0)

# Concatenate along axis 1 (columns)
concatenated_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1 (columns):")
print(concatenated_axis_1)


Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [51]:
#Q.49   Create a function that splits an array into multiple sub-arrays along a specified axis.


# Function to split an array along a specified axis
def split_array(arr, num_splits, axis=0):
    return np.split(arr, num_splits, axis=axis)

# Given array
original_array = np.array([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])

# Split the array along axis 0 (rows) into 3 sub-arrays
split_axis_0 = split_array(original_array, 3, axis=0)
print("Split along axis 0 (rows):")
for sub_array in split_axis_0:
    print(sub_array)
    
# Split the array along axis 1 (columns) into 3 sub-arrays
split_axis_1 = split_array(original_array, 3, axis=1)
print("\nSplit along axis 1 (columns):")
for sub_array in split_axis_1:
    print(sub_array)


Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [52]:
#Q.50  Write a function that inserts and then deletes elements from a given array at specified indices.


# Function to insert and delete elements from the array
def modify_array(arr, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert values at the specified indices
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    
    # Delete values at the specified indices
    arr = np.delete(arr, indices_to_delete)
    
    return arr

# Given array
original_array = np.array([1, 2, 3, 4, 5])

# Indices and values to insert
indices_to_insert = [2, 4]  # Insert at positions 2 and 4
values_to_insert = [10, 11]  # Values to insert

# Indices to delete
indices_to_delete = [1, 3]  # Delete elements at positions 1 and 3

# Apply the function
modified_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified array:", modified_array)


Modified array: [ 1 10  4 11  5]


In [53]:
#Q.51  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.


# Create arr1 with random integers between 1 and 10, with size (5,)
arr1 = np.random.randint(1, 11, size=5)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 6)  # This creates an array [1, 2, 3, 4, 5]

# Perform element-wise addition
result = arr1 + arr2

# Print the arrays and the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise addition result:", result)


Array 1: [5 9 8 5 5]
Array 2: [1 2 3 4 5]
Element-wise addition result: [ 6 11 11  9 10]


In [54]:
#Q.52   Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.


# Create arr1 with integers from 10 to 1 (inclusive)
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10 (inclusive)
arr2 = np.arange(1, 11)

# Perform element-wise subtraction: arr1 - arr2
result = arr1 - arr2

# Print the arrays and the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise subtraction result:", result)


Array 1: [10  9  8  7  6  5  4  3  2  1]
Array 2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [55]:
#Q.53   Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2

# Create arr1 with 5 random integers between 1 and 10
arr1 = np.random.randint(1, 11, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise multiplication result:", result)


Array 1: [8 2 1 4 1]
Array 2: [1 2 3 4 5]
Element-wise multiplication result: [ 8  4  3 16  5]


In [56]:
#Q.54   Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.


# Create arr1 with even integers from 2 to 10 (inclusive)
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5 (inclusive)
arr2 = np.array([1, 2, 3, 4, 5])

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise division result:", result)


Array 1: [ 2  4  6  8 10]
Array 2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [57]:
#Q.55  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


# Create arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Create arr2 with the same numbers as arr1, but reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation: arr1 ** arr2
result = arr1 ** arr2

# Print the arrays and the result
print("Array 1:", arr1)
print("Array 2 (Reversed):", arr2)
print("Element-wise exponentiation result:", result)


Array 1: [1 2 3 4 5]
Array 2 (Reversed): [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


In [58]:
#Q.56  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.



# Function to count occurrences of a substring in a NumPy array of strings
def count_substring_occurrences(arr, substring):
    # Count the occurrences of the substring in each element of the array
    count = np.char.count(arr, substring)
    
    # Return the total count by summing up the individual counts
    return np.sum(count)

# Given array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Substring to search for
substring = 'hello'

# Count occurrences of 'hello' in the array
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", result)


Occurrences of 'hello': 3


In [61]:
#Q.57  Write a function that extracts uppercase characters from a NumPy array of strings.



# Function to extract uppercase characters from a NumPy array of strings
def extract_uppercase(arr):
    # List comprehension to extract uppercase characters from each string in the array
    uppercase_chars = [char for word in arr for char in word if char.isupper()]
    
    return uppercase_chars

# Given array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
result = extract_uppercase(arr)

print("Uppercase characters:", result)


Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [62]:
#Q.58  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


# Function to replace occurrences of a substring in a NumPy array of strings
def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace old_substring with new_substring in each element
    modified_arr = np.char.replace(arr, old_substring, new_substring)
    return modified_arr

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Substring to replace and the new substring
old_substring = 'apple'
new_substring = 'orange'

# Replace occurrences of 'apple' with 'orange'
result = replace_substring(arr, old_substring, new_substring)

print("Modified array:", result)


Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [63]:
#Q.59   Write a function that concatenates strings in a NumPy array element-wise.


# Function to concatenate strings element-wise from two NumPy arrays
def concatenate_strings(arr1, arr2):
    # Use np.char.add() to concatenate the arrays element-wise
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

# Given arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings element-wise
result = concatenate_strings(arr1, arr2)

print("Concatenated array:", result)


Concatenated array: ['HelloOpen' 'WorldAI']


In [64]:
#Q.60   Write a function that finds the length of the longest string in a NumPy array.


# Function to find the length of the longest string in a NumPy array
def longest_string_length(arr):
    # Use np.char.str_len to get the length of each string in the array
    lengths = np.char.str_len(arr)
    
    # Find and return the maximum length
    return np.max(lengths)

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
result = longest_string_length(arr)

print("Length of the longest string:", result)


Length of the longest string: 9


In [65]:
#Q.61  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.


# Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean of the dataset
mean_value = np.mean(dataset)

# Compute the median of the dataset
median_value = np.median(dataset)

# Compute the variance of the dataset
variance_value = np.var(dataset)

# Compute the standard deviation of the dataset
std_deviation_value = np.std(dataset)

# Print the results
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)


Mean: 477.81
Median: 446.0
Variance: 80897.8139
Standard Deviation: 284.4254100814482


In [66]:
#Q.62  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.


# Generate a dataset of 50 random integers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Compute the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the results
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


25th Percentile: 19.5
75th Percentile: 76.75


In [67]:
#Q.63  Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

# Create two arrays representing two sets of variables
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(arr1, arr2)

# Extract the correlation coefficient between arr1 and arr2
correlation = corr_matrix[0, 1]

# Print the correlation coefficient
print("Correlation Coefficient:", correlation)


Correlation Coefficient: -0.9999999999999999


In [68]:
#Q.64  Create two matrices and perform matrix multiplication using NumPy's `dot` function.


# Create two matrices
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 matrix
matrix2 = np.array([[7, 8], [9, 10]])  # 2x2 matrix

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Print the result
print("Matrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [69]:
#Q.65  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

# Generate an array of 50 random integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  # This is also the median
percentile_90 = np.percentile(arr, 90)

# Calculate the first (25th) and third (75th) quartiles
quartile_25 = np.percentile(arr, 25)
quartile_75 = np.percentile(arr, 75)

# Print the results
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("25th Quartile (1st Quartile):", quartile_25)
print("75th Quartile (3rd Quartile):", quartile_75)


10th Percentile: 158.60000000000002
50th Percentile (Median): 473.0
90th Percentile: 810.3000000000001
25th Quartile (1st Quartile): 271.25
75th Quartile (3rd Quartile): 665.5


In [70]:
#Q.66  Create a NumPy array of integers and find the index of a specific element.


# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Specify the element whose index you want to find
element = 40

# Find the index of the element
index = np.where(arr == element)

# Print the index
print(f"Index of {element}: {index[0][0]}")


Index of 40: 3


In [71]:
#Q.67  Generate a random NumPy array and sort it in ascending order.


# Generate a random NumPy array with 10 integers between 1 and 100
arr = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_arr = np.sort(arr)

# Print the original and sorted arrays
print("Original Array:", arr)
print("Sorted Array:", sorted_arr)


Original Array: [  9  91  40  39 100  21  39  89  82  37]
Sorted Array: [  9  21  37  39  39  40  82  89  91 100]


In [73]:
#Q.68  Filter elements >20  in the given NumPy array.



# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Print the result
print("Filtered Array (elements > 20):", filtered_arr)



Filtered Array (elements > 20): [25 42 30]


In [74]:
#Q.69   Filter elements which are divisible by 3 from a given NumPy array.


# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the result
print("Filtered Array (elements divisible by 3):", filtered_arr)


Filtered Array (elements divisible by 3): [12 15]


In [75]:
#Q.70  Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the result
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)


Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [76]:
#Q.71  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.


# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using dtype.byteorder
byte_order = arr.dtype.byteorder

# Print the result
print(f"Byte order of the array: {byte_order}")


Byte order of the array: =


In [77]:
#Q.72  For the given NumPy array, perform byte swapping in place using `byteswap()`.


# Given NumPy array with int32 data type
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the result
print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [80]:
#Q.73  For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`

import numpy as np

# Given NumPy array with int32 data type
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the original and swapped arrays
print("Original Array:", arr)
print("Swapped Array:", swapped_arr)



AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [81]:
#Q.74   For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

import numpy as np
import sys

# Given NumPy array with int32 data type
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's byte order
system_endianness = sys.byteorder

# If the system is little-endian, swap the byte order, otherwise leave it unchanged
if system_endianness == 'little':
    # Swap the byte order if the system is little-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # If the system is big-endian, we don't swap
    swapped_arr = arr

# Print the original and swapped arrays
print("Original Array:", arr)
print("Swapped Array (if needed):", swapped_arr)


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [82]:
#Q.75   For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

import numpy as np
import sys

# Given NumPy array with int32 data type
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's byte order
system_endianness = sys.byteorder

# Check the byte order of the array
array_endianness = arr.dtype.byteorder

# Determine if byte swapping is necessary
if array_endianness == '=':
    # Native byte order (no swap needed)
    print("Byte order is native. No byte swapping needed.")
elif array_endianness != system_endianness:
    # If the byte order of the array is different from the system's byte order, swap is needed
    print("Byte order mismatch! Byte swapping is necessary.")
else:
    # If both byte orders are the same, no swap is needed
    print("Byte order is already compatible with the system. No byte swapping needed.")


Byte order is native. No byte swapping needed.


In [83]:
#Q.76  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

# Create a NumPy array with values from 1 to 10
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in the copied array
copy_arr[0] = 100

# Print both arrays to see if arr1 is affected
print("Original Array (arr1):", arr1)
print("Modified Copy Array (copy_arr):", copy_arr)

# Check if arr1 was affected
if np.array_equal(arr1, copy_arr):
    print("No, arr1 was affected by the change in copy_arr.")
else:
    print("No, arr1 was NOT affected by the change in copy_arr.")


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array (copy_arr): [100   2   3   4   5   6   7   8   9  10]
No, arr1 was NOT affected by the change in copy_arr.


In [84]:
#Q.77  . Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.



# Create a 2D NumPy array (3x3) with random integers between 1 and 100
matrix = np.random.randint(1, 100, size=(3, 3))

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Extract a slice (view) from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in the slice
view_slice[0, 0] = 999

# Print the modified slice
print("\nModified Slice:")
print(view_slice)

# Print the original matrix to see if it is affected
print("\nOriginal Matrix after modification:")
print(matrix)


Original Matrix:
[[41 79  6]
 [26 90 42]
 [27 65 53]]

Modified Slice:
[[999  42]
 [ 65  53]]

Original Matrix after modification:
[[ 41  79   6]
 [ 26 999  42]
 [ 27  65  53]]


In [85]:
#Q.78  . Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

# Create a 4x3 NumPy array with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Print the original array_a
print("Original array_a:")
print(array_a)

# Extract a slice (view) from array_a
view_b = array_a[1:, 1:]

# Add 5 to view_b using broadcasting
view_b += 5

# Print the modified slice (view_b)
print("\nModified view_b (slice):")
print(view_b)

# Print the original array_a to check if it was affected
print("\nOriginal array_a after modifying view_b:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Modified view_b (slice):
[[10 11]
 [13 14]
 [16 17]]

Original array_a after modifying view_b:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


In [86]:
#Q.79  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from 
#       orig_array. Modify an element in `reshaped_view` and check if it  reflects changes in the original `orig_array`.



# Create a 2x4 NumPy array with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Print the original array
print("Original orig_array:")
print(orig_array)

# Reshape the array into a new shape (4x2) without copying
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in the reshaped view
reshaped_view[1, 1] = 99

# Print the reshaped view
print("\nModified reshaped_view:")
print(reshaped_view)

# Print the original array to check if it is affected
print("\nOriginal orig_array after modifying reshaped_view:")
print(orig_array)


Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Modified reshaped_view:
[[ 1  2]
 [ 3 99]
 [ 5  6]
 [ 7  8]]

Original orig_array after modifying reshaped_view:
[[ 1  2  3 99]
 [ 5  6  7  8]]


In [87]:
#Q.80  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` ofelements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


# Step 1: Create a 3x4 NumPy array with random integers between 1 and 10
data = np.random.randint(1, 10, size=(3, 4))

# Print the original data array
print("Original data array:")
print(data)

# Step 2: Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the extracted data_copy array
print("\nExtracted data_copy array (elements > 5):")
print(data_copy)

# Step 3: Modify an element in data_copy
data_copy[0] = 999

# Print the modified data_copy array
print("\nModified data_copy array:")
print(data_copy)

# Step 4: Verify if the original data array is affected
print("\nOriginal data array after modifying data_copy:")
print(data)


Original data array:
[[1 5 1 1]
 [6 9 4 4]
 [7 8 4 2]]

Extracted data_copy array (elements > 5):
[6 9 7 8]

Modified data_copy array:
[999   9   7   8]

Original data array after modifying data_copy:
[[1 5 1 1]
 [6 9 4 4]
 [7 8 4 2]]


In [88]:
#Q.81   Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.



# Step 1: Create two matrices A and B of identical shape (3x3)
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])

# Step 2: Perform element-wise addition
addition_result = A + B

# Step 3: Perform element-wise subtraction
subtraction_result = A - B

# Step 4: Display the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of A and B (A + B):")
print(addition_result)

print("\nSubtraction of A and B (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [89]:
#Q.82   Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


# Step 1: Create matrix C (3x2) and matrix D (2x4)
C = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

D = np.array([[7, 8, 9, 10], 
              [11, 12, 13, 14]])

# Step 2: Perform matrix multiplication using np.dot() or the @ operator
result = np.dot(C, D)

# Step 3: Display the result
print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix multiplication result (C * D):")
print(result)


Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix multiplication result (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [90]:
#Q.83   Create a matrix `E` and find its transpose.

import numpy as np

# Step 1: Create matrix E (e.g., 3x2 matrix)
E = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

# Step 2: Find the transpose of matrix E
E_transpose = E.T

# Step 3: Display the results
print("Matrix E:")
print(E)

print("\nTranspose of Matrix E (E^T):")
print(E_transpose)


Matrix E:
[[1 2]
 [3 4]
 [5 6]]

Transpose of Matrix E (E^T):
[[1 3 5]
 [2 4 6]]


In [93]:
#Q.84  Generate a square matrix `F` and compute its determinant.



# Step 1: Generate a square matrix F (e.g., 3x3 matrix)
F = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Step 2: Compute the determinant of matrix F
det_F = np.linalg.det(F)

# Step 3: Display the results
print("Matrix F:")
print(F)

print("\nDeterminant of matrix F:", det_F)



Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


In [92]:
#Q.85  Create a square matrix `G` and find its inverse.

# Step 1: Create a square matrix G (e.g., 2x2 matrix)
G = np.array([[4, 7], 
              [2, 6]])

# Step 2: Compute the inverse of matrix G
try:
    G_inv = np.linalg.inv(G)
    print("Matrix G:")
    print(G)

    print("\nInverse of matrix G (G^-1):")
    print(G_inv)

except np.linalg.LinAlgError:
    print("Matrix G is singular and cannot be inverted.")


Matrix G:
[[4 7]
 [2 6]]

Inverse of matrix G (G^-1):
[[ 0.6 -0.7]
 [-0.2  0.4]]
